### ISSUE TITLE
panic: interface conversion: sqlparser.Statement is nil, not *sqlparser.CreateTable

### ISSUE THREAD

**Issue by JaisDK** [mpchadwick/dbanon#14]
Hello,
I am getting an error when I run dbanon. Do you know what this error could relate to? The dbanon.log file is empty.

```
root@af1ae37f315b:/app# mysqldump -h mariadb -B oastest | dbanon -config=application/configs/anonymize.yml -log-level=debug > anonymized.sql
panic: interface conversion: sqlparser.Statement is nil, not *sqlparser.CreateTable

goroutine 1 [running]:
github.com/mpchadwick/dbanon/src.findNextTable(0xc00037ae80, 0x39)
        /Users/maxchadwick/go/src/github.com/mpchadwick/dbanon/src/create_table.go:27 +0x417
github.com/mpchadwick/dbanon/src.LineProcessor.ProcessLine(0xaedb67, 0x9, 0xc000272ea0, 0xbb93c0, 0xc0000a8130, 0xc0000839d0, 0xc00037ae80, 0x39, 0xc00037ae40, 0x3b)
        /Users/maxchadwick/go/src/github.com/mpchadwick/dbanon/src/processor.go:25 +0xdd
main.main()
        /Users/maxchadwick/go/src/github.com/mpchadwick/dbanon/main.go:112 +0x706
mysqldump: Got errno 32 on write
```

I've tried running it on both a MySQL 5.6 and MariaDB 10.4 inside a docker container, same result for both.

**Comment by mpchadwick** [comment]
Would it be possible to share the contents from your mysqldump file that causes this to reproduce? Understand sharing a full dump file could definitely have some privacy concerns but if the specific line(s) where it's choking doesn't have any sensitive data I'd like to take a look.

**Comment by mpchadwick** [comment]
Closing due to inactivity.

**Comment by davidegiunchi** [comment]
@mpchadwick I'm having the same problem. I've been able to isolate the error on a small subset of the mysqldump file that doesn't contain any sensitive data. could i share it with you as you previously said?

**Comment by mpchadwick** [comment]
@davidegiunchi - Yes you can definitely share it. I haven't worked on this project for a while, so no promises on the resolution, but if I have some time I'll try to take a look at the issue.

**Comment by davidegiunchi** [comment]
Since is not private at all, i can share it here. with this small .sql file:
```
DROP TABLE IF EXISTS `my_originator`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `my_originator` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `my_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `my_originator_my_id_foreign` (`my_id`),
  CONSTRAINT `my_originator_my_id_foreign` FOREIGN KEY (`my_id`) REFERENCES `my` (`id`) ON UPDATE CASCADE,
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
```
if you pipe it throught dbanon 0.7.1:
```
touch /tmp/a
cat myfile.sql |  dbanon -config=/tmp/a > /tmp/myfile.anon
```
dbanon crash immediatly with this error:
```
panic: interface conversion: sqlparser.Statement is nil, not *sqlparser.CreateTable

goroutine 1 [running]:
github.com/mpchadwick/dbanon/src.findNextTable({0xc000040680, 0x39})
        /Users/maxchadwick/go/src/github.com/mpchadwick/dbanon/src/create_table.go:29 +0x34f
github.com/mpchadwick/dbanon/src.LineProcessor.ProcessLine({{0xeb326f, 0x9}, 0xc000128c60, {0x103c540, 0xc00011a0c8}, 0xc0001244b0}, {0xc000040680, 0x39})
        /Users/maxchadwick/go/src/github.com/mpchadwick/dbanon/src/processor.go:25 +0xb7
main.main()
        /Users/maxchadwick/go/src/github.com/mpchadwick/dbanon/main.go:114 +0x86d
```

it seems to me that the problem is originated by the **CONSTRAINT** line: if i remove it, dbanon doesn't crash
